// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHlqRNMF4bvHDYLY2RyJ_gYVISYfMbyes',
    appId: '1:98602016873:android:08537b5d0c21b249ff02f8',
    messagingSenderId: '98602016873',
    projectId: 'zakoota-e4451',
    storageBucket: 'zakoota-e4451.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZlxccNTcRKEJa3-SjynJfy-OAntoE9Wc',
    appId: '1:98602016873:ios:9272ea48e0b9ebd8ff02f8',
    messagingSenderId: '98602016873',
    projectId: 'zakoota-e4451',
    storageBucket: 'zakoota-e4451.firebasestorage.app',
    androidClientId: '98602016873-aor9st0b1uss7r8uv86dsn987vivun1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZlxccNTcRKEJa3-SjynJfy-OAntoE9Wc',
    appId: '1:98602016873:ios:9272ea48e0b9ebd8ff02f8',
    messagingSenderId: '98602016873',
    projectId: 'zakoota-e4451',
    storageBucket: 'zakoota-e4451.firebasestorage.app',
    androidClientId: '98602016873-aor9st0b1uss7r8uv86dsn987vivun1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkoUmgtRLYFOImTWfxAdznGWe5mdkydaw',
    appId: '1:98602016873:web:674f973bdea5aeb1ff02f8',
    messagingSenderId: '98602016873',
    projectId: 'zakoota-e4451',
    authDomain: 'zakoota-e4451.firebaseapp.com',
    storageBucket: 'zakoota-e4451.firebasestorage.app',
    measurementId: 'G-CRX66GK6B6',
  );
}
